# Initalize
init:
  - git config --global core.autocrlf true

# Install services
services:
  - iis

# Install script
install:
    - ps: >-
        #Install WebDeploy
        choco install webdeploy

        #Start Services
        Start-Service W3SVC
        Start-Service WMSVC
        Start-Service msdepsvc

        #Turn Firewall Off
        netsh advfirewall set allprofiles state off

# Build script
build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\build.ps1 -Target "AppVeyor"

# Test settings
test: off

# Branches whitelist
branches:
  only:
    - master
    - develop
